// ODIN entity mapping
// Map Home Assistant entity IDs to ODIN UI slots.
// Updated 2026-05-05 — standardized naming convention.

export const haMap = {
  presence: {
    person: "person.chris_farrell",
    device_tracker: "device_tracker.chris_iphone_17_pro",
  },
  rooms: {
    "Living Room": {
      lights: [
        "light.living_room",
        "light.living_room_floor_lamp",
        "light.living_room_lamp_a",
        "light.living_room_lamp_b",
        "light.living_room_hue_play_a",
        "light.living_room_hue_play_b",
      ],
      scenes: {
        "Coming Home at Night": "scene.living_room_lights_shine",
        Movie: "scene.living_room_lights_movie",
        Cooking: "scene.living_room_lights_bright",
        Chill: "scene.living_room_lights_relax",
      },
      occupancy: "binary_sensor.living_room_occupancy",
      media_player: "media_player.living_room_speakers",
    },
    Kitchen: {
      lights: [
        "light.kitchen",
        "light.kitchen_island_a",
        "light.kitchen_island_b",
        "light.kitchen_cabinet_strip_a",
        "light.kitchen_cabinet_strip_b",
        "light.kitchen_counter_lamp_a",
        "light.kitchen_counter_lamp_b",
      ],
      scenes: {
        "Coming Home at Night": "scene.kitchen_lights_shine",
        Movie: "scene.kitchen_lights_movie",
        Cooking: "scene.kitchen_lights_bright",
        Chill: "scene.kitchen_lights_relax",
      },
      occupancy: "",
    },
    Bedroom: {
      lights: [
        "light.bedroom",
        "light.bedroom_lamp_a",
        "light.bedroom_lamp_b",
      ],
      scenes: {
        Bedtime: "scene.bedroom_lights_storybook",
        "Entering Room": "scene.bedroom_lights_read",
      },
      occupancy: "binary_sensor.bedroom_occupancy",
      media_player: "media_player.bedroom_speaker",
    },
    Office: {
      lights: [
        "light.office",
        "light.office_lamp",
        "light.office_light_strip",
      ],
      scenes: {
        "Deep Work": "scene.office_bright",
        "Entering Room": "scene.office_read",
      },
      occupancy: "binary_sensor.office_occupancy",
    },
    "Upstairs Bathroom": {
      lights: [
        "light.bathroom",
        "light.bathroom_light_strip",
      ],
      scenes: {
        Nightlight: "scene.bathroom_lights_tropical_twilight",
      },
      occupancy: "binary_sensor.bathroom_occupancy",
    },
    "Lower Bath": {
      lights: [],
      scenes: {},
      occupancy: "",
    },
  },
  presence_zones: {
    "Living Room": "binary_sensor.living_room_occupancy",
    "Living Room Couch": "binary_sensor.living_room_couch",
    "Living Room Enter/Exit": "binary_sensor.living_room_enter_exit",
    "Office": "binary_sensor.office_occupancy",
    "Office Desk": "binary_sensor.office_desk",
    "Office Lucy Zone": "binary_sensor.office_zone_lucy",
    "Office Enter/Exit": "binary_sensor.office_enter_exit",
    "Bedroom": "binary_sensor.bedroom_occupancy",
    "Bedroom Bed": "binary_sensor.bedroom_bed",
    "Bedroom Enter/Exit": "binary_sensor.bedroom_enter_exit",
    "Bathroom": "binary_sensor.bathroom_occupancy",
  },
  climate: {
    zones: [
      { name: "Home", entity: "climate.thermostat" },
    ],
    temperature: "sensor.thermostat_temperature",
    humidity: "sensor.thermostat_humidity",
  },
  garage: {
    cover: "cover.garage_door",
    motor: "",
    openings: "",
    button: "event.garage_door_button",
    button_battery: "sensor.garage_door_button_battery_sensor",
  },
  security: {
    alarm: "",
    sensors: [
      { name: "Front Door", entity: "binary_sensor.front_door_contact" },
      { name: "Back Door", entity: "binary_sensor.back_door" },
      { name: "Bedroom Door", entity: "binary_sensor.bedroom_door" },
      { name: "Bathroom Door", entity: "binary_sensor.bathroom_door" },
      { name: "Front Door Person", entity: "binary_sensor.front_door_person_detected" },
      { name: "Front Door Vehicle", entity: "binary_sensor.front_door_vehicle_detected" },
      { name: "Front Door Pet", entity: "binary_sensor.front_door_pet_detected" },
      { name: "Front Door Visitor", entity: "binary_sensor.front_door_visitor_detected" },
      { name: "Front Door Motion", entity: "binary_sensor.front_door_motion" },
    ],
    siren: "siren.front_door",
    lock: "",
  },
  cameras: {
    doorbell: "camera.front_door",
    motion: "binary_sensor.front_door_motion",
    person: "binary_sensor.front_door_person_detected",
    vehicle: "binary_sensor.front_door_vehicle_detected",
    pet: "binary_sensor.front_door_pet_detected",
    visitor: "binary_sensor.front_door_visitor_detected",
    day_night: "sensor.front_door_day_night_state",
    others: [],
  },
  media: {
    tv: "media_player.living_room_tv",
    tv_android: "media_player.living_room_tv_android",
    tv_remote: "remote.living_room_tv",
    living_room_speakers: "media_player.living_room_speakers",
    bedroom_speaker: "media_player.bedroom_speaker",
    spotify: "media_player.spotify",
  },
  air_quality: {
    purifier: "fan.air_purifier",
    aqi: "sensor.air_purifier_quality",
    pm25: "sensor.air_purifier_pm25",
  },
  energy: {
    usage_to_date: "sensor.electric_usage_this_bill",
    forecasted_usage: "sensor.electric_usage_forecast",
    typical_usage: "sensor.electric_typical_usage",
    cost_to_date: "sensor.electric_cost_this_bill",
    forecasted_cost: "sensor.electric_cost_forecast",
    typical_cost: "sensor.electric_typical_cost",
    bill_start: "sensor.electric_bill_start_date",
    bill_end: "sensor.electric_bill_end_date",
  },
  bedroom_fan: {
    switch: "switch.bedroom_fan",
    power: "sensor.bedroom_fan_power_live",
    power_total: "sensor.bedroom_fan_power_total",
  },
  xbox: {
    online: "binary_sensor.xbox_online",
    in_game: "binary_sensor.xbox_in_game",
    game_pass: "binary_sensor.xbox_game_pass",
    status: "sensor.xbox_status",
    now_playing: "sensor.xbox_now_playing",
    last_online: "sensor.xbox_last_online",
    gamerscore: "sensor.xbox_gamerscore",
    followers: "sensor.xbox_followers",
    following: "sensor.xbox_following",
    friends: "sensor.xbox_friends",
    in_party: "sensor.xbox_in_party",
    gamerpic: "image.xbox_gamerpic",
    avatar: "image.xbox_avatar",
    now_playing_image: "image.xbox_now_playing",
  },
  phone: {
    battery: "sensor.iphone_battery",
    battery_state: "sensor.iphone_battery_state",
    location_permission: "sensor.iphone_location_permission",
  },
  calendars: [
    { name: "Chris", entity: "calendar.cdfarrell19_gmail_com" },
    { name: "Birthdays", entity: "calendar.birthdays" },
    { name: "US Holidays", entity: "calendar.holidays_in_united_states" },
  ],
  weather: {
    home: "weather.home",
    nws: "weather.nws_38_80174912345508_94_4437722027588_klxt",
  },
  scripts: {
    goodnight: "script.goodnight",
    wake_up: "script.wake_up",
    relax: "script.relax",
    cinema: "script.cinema",
    evaluate_arrival: "script.evaluate_arrival_confidence",
  },
  automations: {
    front_door_after_dark: "automation.front_door_opens_full_lights_after_dark",
    garage_button: "automation.garage_door_wall_button",
    bedroom_fan_on_night: "automation.bedroom_fan_turn_on_at_night",
    bedroom_fan_off_morning: "automation.bedroom_fan_turn_off_in_morning",
    bedroom_lights_on: "automation.bedroom_auto_lights_on_presence",
    bedroom_lights_off: "automation.bedroom_auto_lights_off_no_presence",
    office_lights_on: "automation.office_lights_on",
    office_lights_off: "automation.office_lights_off",
    movie_mode_on: "automation.living_room_movie_mode_on",
    movie_mode_off: "automation.living_room_movie_mode_off",
  },
  voice_satellites: [] as { name: string; entity: string }[],
} as const;

export type HaMap = typeof haMap;
